
= Swift / NWChemEx Collaboration Scripts

== Installations

=== Bebop

==== Login

+/home/wozniak/Public/sfw/bebop/login/swift-t-2018-05-16/stc/bin+

==== Compute

== Demos

=== Simple Swift/T

Use the +run+ scripts to ease use:

----
$ ./run-bebop-login.sh 0-hello.swift
trace: Hello World

$ ./run-bebop-login.sh 1-loop.swift
hello: 0
hello: 3
hello: 2
hello: 1

$ mpiexec -n 4 ./program.sh
program: 0 / 4
program: 1 / 4
program: 3 / 4
program: 2 / 4

$ ./run-bebop-login.sh -n 5 2-launch.swift
program: id=3 0 / 4
program: id=3 2 / 4
program: id=3 3 / 4
program: id=3 1 / 4
...
----

=== C++ library

library.h::
The original application C++ library header

library.cxx::
The original application C++ library implementation

==== Tcl interface

library.i::
The SWIG interface file to generate the Tcl -> C++ binding

library_wrap_tcl.cxx::
The SWIG-generated Tcl C++ wrapper

libtcllibrary.so::
Generated by Makefile- the Tcl -> C++ binding code

pkgIndex.tcl::
Generated by Makefile- the Tcl package information

make-package.tcl::
Used by Makefile- makes pkgIndex.tcl

----
$ ./build-bebop.sh tcl
$ ./run-bebop-login.sh 3-cxx-tcl.swift
----

==== Python interface

library_wrap_py.cxx::
The pybind C++ wrapper

----
$ ./build-bebop.sh python
$ ./run-bebop-login.sh 4-cxx-py.swift
----

NOTE: Python is very sensitive to its environment, and
must be carefully compiled and run with the same
environment.
http://pybind11.readthedocs.io/en/master/faq.html#importerror-dynamic-module-does-not-define-init-function[See here].
If you get these errors, Wozniak may be able to help.
