
= Swift / NWChemEx Collaboration Scripts

== Installations

=== Bebop

==== Login

----
/home/wozniak/Public/sfw/bebop/login/swift-t-2018-05-22/stc/bin
----

==== Compute

== Demos

The scripts are currently set up to report a lot of configuration
information to help in debugging.

=== Simple Swift/T

Use the +run+ scripts to load the right environment variables for the system.
Note that the arguments to the run script are simply passed to the +swift-t+
program.

----
# Hello World
$ ./run-bebop-login.sh 0-hello.swift
trace: Hello World

# Hello World - no script!
$ PATH=/home/wozniak/Public/sfw/bebop/login/swift-t-2018-05-22/stc/bin:$PATH
$ swift-t -E 'trace("Hello World");'
trace: Hello World

# Simple MPI job launch with rank number line prefixes (no Swift/T)
$ PATH=/soft/spack-0.10.1/opt/spack/linux-centos7-x86_64/gcc-7.1.0/mpich-3.2-bsq4vhrrnuyxqel6zlzokwtprddew5ad/bin
$ mpiexec -l -n 4 ./program.sh
program: 0 / 4
program: 1 / 4
program: 3 / 4
program: 2 / 4

# Many tasks in a parallel loop
# Note that the Swift/T tasks are load-balanced across worker ranks
$ ./run-bebop-login.sh -l -n 4 1-loop.swift
[2] hello: 0
[1] hello: 1
[0] hello: 2
[2] hello: 3

# Many parallel tasks in a parallel loop
$ ./run-bebop-login.sh -n 5 2-launch.swift
program: id=3 0 / 4
program: id=3 2 / 4
program: id=3 3 / 4
program: id=3 1 / 4
...
----

=== C++ library

Use the build-*.sh scripts to build with the right environment variables
for the system.  Note that the arguments to this script
are simply passed to the Makefile, which does the real work.

library.h::
The original application C++ library header

library.cxx::
The original application C++ library implementation

==== Tcl interface

library.i::
The SWIG interface file to generate the Tcl -> C++ binding

library_wrap_tcl.cxx::
The SWIG-generated Tcl C++ wrapper

libtcllibrary.so::
Generated by Makefile- the Tcl -> C++ binding code

pkgIndex.tcl::
Generated by Makefile- the Tcl package information

make-package.tcl::
Used by Makefile- makes pkgIndex.tcl

----
# Build the shared object
$ ./build-bebop.sh tcl

# Run it in Swift/T/Tcl
$ ./run-bebop-login.sh 3-cxx-tcl.swift
...
Call to f().
----

==== Python interface

library_wrap_py.cxx::
The pybind C++ wrapper

libpylibrary.so::
Generated by Makefile- the Python -> C++ binding code

test.py::
A plain Python test program to test the pybind-generated module

----
# Build the shared object
$ ./build-bebop.sh python

# Run it in plain Python
$ PATH=/soft/anaconda3/5.0.0/envs/tensorflow/bin:$PATH
$ python test.py
Call to f().

# Run it in Swift/T/Python
$ ./run-bebop-login.sh 4-cxx-py.swift
...
Call to f().
----

NOTE: Python is very sensitive to its environment, and
must be carefully compiled and run with the same
environment.
http://pybind11.readthedocs.io/en/master/faq.html#importerror-dynamic-module-does-not-define-init-function[See here].
If you get these errors, Wozniak may be able to help.
